[wazuh_managers]
wazuh-mgr-1 ansible_host=10.21.232.220 ansible_user=waserver

[wazuh_managers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/rpi/misp/wazuh_ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
